PLATTA-4843 images with url special chars should be url encoded
City-of-Helsinki/drupal-module-helfi-azure-fs pull request #16
Opened 2023-06-14 11:57 UTC by dragos-dumi-ibm

Images with for example + in their name should be outputed with the + sign url encoded, so that nginx will interpret that correctly, not as space

2023-06-20 09:51 UTC, juho-lehmonen requested changes

2023-06-20 09:51 UTC, juho-lehmonen commented on src/Flysystem/Azure.php
> +      return UrlHelper::encodePath($this->fileUrlGenerator->generateString($uri));
Should the whole URL or only the URI be url-encoded? This was caught by the automated tests.

2023-06-21 05:15 UTC, tuutti commented
I wonder if it would be safer to just rename all files to have no special characters. We already convert spaces to `_` here: https://github.com/City-of-Helsinki/drupal-module-helfi-azure-fs/blob/main/helfi_azure_fs.module#L40 

We could just run filename through `preg_replace('/[^A-z0-9_-]/', '_', $filename);` or something

2023-06-21 08:43 UTC, dragos-dumi-ibm commented
@tuutti @juho-lehmonen  indeed is better with just replacing the +, if already done and agreed for space
updated the PR and included the + sign in the existing test
I guess the encodePath path on uri we should still keep it for other potential cases

2023-06-21 09:02 UTC, dragos-dumi-ibm commented on src/Flysystem/Azure.php
> +      return UrlHelper::encodePath($this->fileUrlGenerator->generateString($uri));
@juho-lehmonen url encidng the uri will break the fs://
I guess the test is bit wrong, as generateString says in doc "Creates a root-relative web-accessible URL string."  and testing it, it indeed returns without the host 
we could not encode it at all, but I guess there could be other characters that will break the url.... and anyhow other chars should be encoded I guess
ex: 
/kasko-assets/sites/default/files/styles/media_library/azure/medium_IPI_kahvila_Emma_Palomäki_Barista_0853_4.jpg

VS
 
/kasko-assets/sites/default/files/styles/media_library/azure/medium_IPI_kahvila_Emma_Paloma%CC%88ki_Barista_0853_4.jpg?itok=Nt1SxKZx

2023-06-21 10:06 UTC, tuutti approved these changes
Looks good

2023-06-21 10:13 UTC, tuutti approved these changes

2023-06-21 10:36 UTC, merged